### PR TITLE
Fix meta merge and memory leak on Vue Meta@2

### LINKED ISSUE #123: Possible memory leak with new version of VueMeta@2
Updating `nuxt@2.9.2` and `vue-meta@2.2.0`, and browsing the website, cause Google Chrome to crash.

You can see what's happening [here](https://github.com/nuxt/nuxt.js/issues/6338#issuecomment-531751641).

I'm trying to reproduce the issue in this [codesandbox](https://codesandbox.io/s/nuxt-vue-meta-220-bug-rrd1z).

### PR DESCRIPTION
**Pull request by Zsavajji**
Should fix #123 .
Thanks to @pimlie for the very precious advice, now head gets injected and merged only for the components which have the jsonld function defined.

### CODE REVIEW

File: src/mergeHead.ts [hunk 1]
```diff
@@ -0,0 +1,64 @@
...
+
+    const hash = XXH.h32(innerHTML, 0).toString(16);
+    const hid = `nuxt-jsonld-${hash}`;
+
+    return {
+      script: [
+        {
+          hid,
+          type: 'application/ld+json',
+          innerHTML,
```
Comment (pimlie) [inline src/mergeHead.ts]: As of vue-meta v2.2 you can set a json prop directly

File: src/mergeHead.ts [hunk 2]
```diff
@@ -0,0 +1,64 @@
...
+        },
+      ],
+      __dangerouslyDisableSanitizersByTagID: {
+        [hid]: ['innerHTML'],
```
Comment (pimlie) [inline src/mergeHead.ts]: Not needed if you use the json prop

File: src/mergeHead.ts [hunk 3]
```diff
@@ -0,0 +1,64 @@
...
+    if (!head) { return {} }
+
+    if (!Array.isArray(head)) {
+      return head;
+    }
+
+    return head.reduce((acc, i) => {
+      switch (typeof i) {
+        case 'function':
+          acc = { ...acc, ...i.call(this) }
```
Comment (pimlie) [inline src/mergeHead.ts]: reduce + spread is considered an anti pattern: https://www.richsnapp.com/blog/2019/06-09-reduce-spread-anti-pattern

File: src/createMixin.ts [hunk 4]
```diff
@@ -27,33 +16,10 @@ export default (options: Options = {}): JsonldMixin => {
...
-    head(this: Vue) {
-      if (!this.$options || typeof this.$options.jsonld !== 'function') {
-        return {};
-      }
-
-      if (this.$options.jsonld.call(this) === null) {
-        return {};
+    beforeCreate (this: Vue) {
+      if (this.$options && typeof this.$options.jsonld === 'function') {
+        this.$options.head = mergeHead.call(this, mergedOptions)
```
Comment (pimlie) [inline src/createMixin.ts]: I am slightly worried that you will loose the reactivity of head with this approach, did you check that?

It would probably be an improvement to set the original head function as a second computed prop here. By returning a function in mergeHead vue-meta will always create a computed prop `$metaInfo`. Use that same approach here for the original head (if its a function) and create another computed prop in your mergeHead function. That way you never have to call a head function yourself (you can use the computed prop directly) and because you use the computed prop reactivity should not be lost.

Comment (pimlie) [reply src/createMixin.ts]: Another benefit of using a computed prop is that Vue takes care of caching. If you call the head fn manually, the fn will be called everytime the meta of any component is updated. A computed prop is cached in Vue and only updates when one its own 'dependencies' changes.

File: src/mergeHead.ts [hunk 5]
```diff
@@ -0,0 +1,64 @@
...
+}
+
+const stringifyLD = (options: Options) => function () {
+  const jsonLd = this.$options.jsonld.call(this);
+
+  if (jsonLd !== null) {
+    const stringifiedJson = JSON.stringify(jsonLd, null, options.space);
+    const innerHTML = options.space === 0 ? stringifiedJson : `\n${stringifiedJson}\n`;
+
+    const hash = XXH.h32(innerHTML, 0).toString(16);
```
Comment (pimlie) [inline src/mergeHead.ts]: Hashing is always cpu heavy. From the look of it you just need a unique variable here. You could also set an internal prop which you increment. 
```js
let jsonId = 1
...

const stringifyLD = (options: Options) => function () {
   const hash = jsonId++
...
```

File: src/mergeHead.ts (hunk 1 above)
Comment (pimlie) [reply src/mergeHead.ts]: True, you cant change that at the moment

Comment (Zsavajji) [reply src/mergeHead.ts]: Will leave this as is, but i don't actually see the utility of having the `space` option at all, since in production head code gets minified most times.

Comment (Zsavajji) [reply src/mergeHead.ts]: Will leave this as is, but i don't actually see the utility of having the `space` option at all, since in production head code gets minified most times.

File: src/createMixin.ts (hunk 4 above)
Comment (Zsavajji) [reply src/createMixin.ts]: Done in the new commit! Set the computed property for head and also for LD-JSON, even if i don't see any meaningful usage for reactive json-ld 🤔

File: src/mergeHead.ts (hunk 5 above)
Comment (Zsavajji) [reply src/mergeHead.ts]: Thank you, here i copied the original implementation, but hashing is absolutely not needed. Removed and removed associated tests

Comment (ymmooot) [reply src/mergeHead.ts]: This approach of making `hid` changes `hid` by each request.
It causes problems when you make cache of HTML with ETag.
Please check this similar issue: https://github.com/ymmooot/nuxt-jsonld/issues/58. 🙏

Comment (Zsavajji) [reply src/mergeHead.ts]: Uh, did not take account of this need. Wouldn't it be enough to use the name of the component that injected the jsonLD?

Comment (ymmooot) [reply src/mergeHead.ts]: Components can be used multiple time, so it will not be unique id.
Another approach that I wanted to try is gathering each json as an array and putting the array into root component. This approach does not need to make hid each json.

Anyway, you can just use hash just like before.
Avoiding using hash should be another issue.

Comment (Zsavajji) [reply src/mergeHead.ts]: Yes, correct approach. Will put it back, so we can maybe close this issue :)
