### PR TITLE
Fix bug that removes all meta tags

### LINKED ISSUE #3: Using jsonld() removes all other content from the head of the website
Hi There,

I added this package as described and when you use this package it removes all existing meta tags specified in the `nuxt.config.js` file

This happens on your example project also, this makes this package pretty much **unusable**

### PR DESCRIPTION
**Pull request by ymmooot**
fix #3

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -1,32 +1,43 @@
...
-        res1.__dangerouslyDisableSanitizersByTagID = {
-          ...(res1.__dangerouslyDisableSanitizersByTagID || {}),
-          ...res2.__dangerouslyDisableSanitizersByTagID,
-        };
+  return function head() {
+    const res1 = getValue(fromVal, this);
+    const res2 = getValue(toVal, this);
+
+    if (res2.script) {
+      const hasScript = (res1.script || []).some(s => s.hid === res2.script[0].hid);
```
Comment (RyoNkmr) [inline src/index.js]: [IMO]

```diff
+      const fromValScript = res1.script || [];
+      const hasScript = fromValScript.some(s => s.hid === res2.script[0].hid);
-      const hasScript = (res1.script || []).some(s => s.hid === res2.script[0].hid);

       if (!hasScript) {
+        res1.script = [...fromValScript, ...res2.script];
-        res1.script = res1.script ? res1.script.concat(res2.script) : res2.script;
```
